// Getting a map document in and out of the browser.
//
// Separated from main.ts because none of it touches the scene, the tools
// or the camera: it is File / Blob / clipboard plumbing plus the strict
// decoder, and it is the part with error paths worth reading.

import { Maps } from '@mydrunner/shared';

/** Parse a picked file. Throws with the decoder's own message, which
 *  names the offending field ("spawns[2].yaw must be a finite number") —
 *  hand-edited maps are the common case and that message is the whole
 *  answer, so callers should surface it rather than replace it. */
export async function readMapFile(file: File): Promise<Maps.MapDoc> {
  return Maps.decodeMapDoc(JSON.parse(await file.text()));
}

/** Trigger a download of the document as JSON. */
export function downloadJson(doc: Maps.MapDoc): string {
  const blob = new Blob([Maps.encodeMapDoc(doc)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${doc.id}.json`;
  a.click();
  URL.revokeObjectURL(url);
  return a.download;
}

/** The .ts module form — what actually gets a map into the game, since
 *  registry.ts imports committed maps as modules rather than JSON. */
export function moduleSource(doc: Maps.MapDoc): string {
  return (
    `// Generated by the level editor. Add to AUTHORED in map/registry.ts.\n` +
    `import type { MapDoc } from '../mapDoc.js';\n\n` +
    `export const ${moduleIdentifier(doc.id)}: MapDoc = ${Maps.encodeMapDoc(doc)};\n`
  );
}

/** A map id as a valid JS identifier. Ids come from a text field, so
 *  they can hold anything a user typed. */
export function moduleIdentifier(id: string): string {
  const cleaned = id.replace(/[^A-Za-z0-9_]/g, '_');
  if (!cleaned) return 'authoredMap';
  return /^[0-9]/.test(cleaned) ? `map_${cleaned}` : cleaned;
}

/** Copy text to the clipboard. Resolves false when the browser refuses —
 *  clipboard access needs a secure context and a user gesture, and
 *  silently doing nothing would look like the button was broken. */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
